import { isAdminRole } from './permissions';

// First-accessible-route lookup, in the same top-to-bottom order as the sidebar
// (DashboardPage.tsx). The first entry whose permission the user holds wins.
const ROUTE_BY_PERMISSION: { permission: string | string[]; route: string }[] = [
  { permission: 'dashboard.view', route: '/dashboard' },
  { permission: 'users.read', route: '/admin/users' },
  { permission: 'roles.read', route: '/admin/roles' },
  { permission: 'departments.read', route: '/admin/departments' },
  { permission: 'positions.read', route: '/admin/positions' },
  { permission: 'company.read', route: '/admin/company' },
  { permission: 'properties.read', route: '/admin/properties' },
  { permission: 'tenants.read', route: '/admin/tenants' },
  { permission: 'leases.read', route: '/admin/leases' },
  { permission: 'crm-leads.read', route: '/admin/crm/leads' },
  { permission: 'crm-campaigns.read', route: '/admin/crm/campaigns' },
  { permission: 'parking-overview.read', route: '/admin/parking' },
  { permission: 'parking-allocations.read', route: '/admin/parking/allocations' },
  { permission: 'parking-visitors.read', route: '/admin/parking/visitors' },
  { permission: 'parking-gate-logs.read', route: '/admin/parking/gate-logs' },
  { permission: 'parking-vehicles.read', route: '/admin/parking/vehicles' },
  { permission: 'billing-dashboard.read', route: '/admin/billing/dashboard' },
  { permission: 'billing-invoices.read', route: '/admin/billing/invoices' },
  { permission: 'billing-schedules.read', route: '/admin/billing/schedules' },
  { permission: 'charge-category.read', route: '/admin/billing/charge-categories' },
  { permission: 'billing-charge-types.read', route: '/admin/billing/charge-types' },
  { permission: 'meter.read', route: '/admin/billing/meter-setup' },
  { permission: 'billing-settings.read', route: '/admin/billing/settings' },
  { permission: 'ar-receipts.read', route: '/admin/ar/receipts' },
  { permission: 'ar-aging.read', route: '/admin/ar/aging' },
  { permission: 'ar-collections.read', route: '/admin/ar/collections' },
  { permission: 'ar-refunds.read', route: '/admin/ar/refunds' },
  { permission: 'ar-statements.read', route: '/admin/ar/statements' },
  { permission: 'ar-credits.read', route: '/admin/ar/credits' },
  { permission: 'ap-invoices.read', route: '/admin/ap/invoices' },
  { permission: 'ap-vouchers.read', route: '/admin/ap/vouchers' },
  { permission: 'ap-expenses.read', route: '/admin/ap/expenses' },
  { permission: 'finance-coa.read', route: '/admin/gl/accounts' },
  { permission: 'finance-journal.read', route: '/admin/gl/journal-entries' },
  { permission: 'finance-fiscal-periods.read', route: '/admin/gl/fiscal-periods' },
  { permission: 'finance-trial-balance.read', route: '/admin/gl/trial-balance' },
  { permission: 'finance-pnl.read', route: '/admin/gl/pnl' },
  { permission: 'finance-balance-sheet.read', route: '/admin/gl/balance-sheet' },
  { permission: 'finance-cash-flow.read', route: '/admin/gl/cash-flow' },
  { permission: 'finance-budgets.read', route: '/admin/budgets' },
  { permission: 'finance-assets.read', route: '/admin/assets' },
  { permission: 'finance-banking.read', route: '/admin/banking' },
  { permission: 'finance-gateway.read', route: '/admin/banking/gateway-transactions' },
  { permission: 'workflows-tasks.read', route: '/tasks' },
  { permission: 'workflows-engine.read', route: '/admin/workflows' },
  { permission: 'maintenance-dashboard.read', route: '/admin/maintenance' },
  { permission: 'maintenance-tickets.read', route: '/admin/maintenance/tickets' },
  { permission: 'maintenance-technicians.read', route: '/admin/maintenance/technicians' },
  { permission: 'maintenance-sla.read', route: '/admin/maintenance/sla-config' },
  { permission: 'maintenance-pm.read', route: '/admin/maintenance/pm' },
  { permission: 'maintenance-pm-calendar.read', route: '/admin/maintenance/pm/calendar' },
  { permission: 'facility-assets.read', route: '/admin/facility/assets' },
  { permission: 'facility-cam.read', route: '/admin/facility/cam-costs' },
  { permission: 'facility-schedule.read', route: '/admin/facility/schedule' },
  { permission: 'inventory-dashboard.read', route: '/admin/inventory/dashboard' },
  { permission: 'inventory-items.read', route: '/admin/inventory/items' },
  { permission: 'inventory-stock.read', route: '/admin/inventory/stock' },
  { permission: 'inventory-stores.read', route: '/admin/inventory/stores' },
  { permission: 'inventory-movements.read', route: '/admin/inventory/movements' },
  { permission: 'inventory-purchase-req.read', route: '/admin/inventory/purchase-requisitions' },
  { permission: 'housekeeping-dashboard.read', route: '/admin/housekeeping/dashboard' },
  { permission: 'housekeeping-tasks.read', route: '/admin/housekeeping' },
  { permission: 'housekeeping-schedules.read', route: '/admin/housekeeping/schedules' },
  { permission: 'housekeeping-zones.read', route: '/admin/housekeeping/zones' },
  { permission: 'housekeeping-inspections.read', route: '/admin/housekeeping/inspections' },
  { permission: 'security-dashboard.read', route: '/admin/security/dashboard' },
  { permission: 'security-incidents.read', route: '/admin/security/incidents' },
  { permission: 'security-patrol.read', route: '/admin/security/patrol' },
  { permission: 'security-patrol-schedules.read', route: '/admin/security/patrol/schedules' },
  { permission: 'security-patrol-scan.read', route: '/admin/security/patrol/scan' },
  { permission: 'security-access-events.read', route: '/admin/security/access-events' },
  { permission: 'security-blacklist.read', route: '/admin/security/blacklist' },
  { permission: 'documents.read', route: '/documents' },
  { permission: ['notifications.send', 'notifications.logs', 'notifications.manage'], route: '/notifications' },
  { permission: 'mall-dashboard.read', route: '/admin/mall' },
  { permission: 'mall-shops.read', route: '/admin/mall/shops' },
  { permission: 'mall-gto.read', route: '/admin/mall/gto' },
  { permission: 'mall-cam.read', route: '/admin/mall/cam' },
  { permission: 'mall-events.read', route: '/admin/mall/events' },
  { permission: 'mall-footfall.read', route: '/admin/mall/footfall' },
  { permission: 'mall-pos.read', route: '/admin/mall/pos' },
  { permission: 'community-admin.read', route: '/admin/community' },
  { permission: 'community-quick-actions.read', route: '/admin/portal/quick-actions' },
  { permission: 'community-analytics.read', route: '/admin/portal/analytics' },
  { permission: 'community-access-cards.read', route: '/admin/access-cards' },
  { permission: 'community-branding.read', route: '/admin/portal/branding' },
  { permission: 'condo-meters.read', route: '/admin/condo/smart-meters' },
  { permission: 'condo-funds.read', route: '/admin/condo/funds' },
  { permission: 'condo-meetings.read', route: '/admin/condo/meetings' },
  { permission: 'condo-bylaws.read', route: '/admin/condo/bylaws' },
  { permission: 'portal.read', route: '/portal' },
  { permission: 'reports-executive.read', route: '/admin/bi' },
  { permission: 'reports-bi.read', route: '/admin/bi/reports' },
  { permission: 'reports-anomalies.read', route: '/admin/bi/anomalies' },
  { permission: 'reports-list.read', route: '/reports' },
  { permission: 'developer-integrations.read', route: '/admin/developer/integrations' },
  { permission: 'developer-webhooks.read', route: '/admin/developer/webhooks' },
  { permission: 'developer-api-keys.read', route: '/admin/developer/api-keys' },
  { permission: 'developer-bms.read', route: '/admin/developer/bms' },
  { permission: 'settings-security.read', route: '/settings/security' },
  { permission: 'settings-notifications.read', route: '/settings/notifications' },
  { permission: 'settings-profile.read', route: '/settings/profile' },
];

/**
 * Where to land a user right after login: the first sidebar destination they can
 * actually see, in sidebar order — not always /dashboard. Admins (who bypass
 * permission checks entirely) and anyone with no matching permission at all still
 * fall back to /dashboard, since that route itself isn't permission-gated.
 */
export function getDefaultRoute(permissions: string[], roles: string[] = []): string {
  if (isAdminRole(roles)) return '/dashboard';
  for (const entry of ROUTE_BY_PERMISSION) {
    const required = Array.isArray(entry.permission) ? entry.permission : [entry.permission];
    if (required.some((p) => permissions.includes(p))) return entry.route;
  }
  return '/dashboard';
}
