/* ── P-Unit Zone options ──────────────────────
   Retail/trade zone categories used to classify a unit within the property. */
export const ZONE_OPTIONS = [
  'Eyewears & Watches',
  'Cosmetics & Skin Cares',
  'Quick Meal Restaurant',
  'International Fashion',
  'Jewellery/Gold & Silver',
  'Departmental Store',
  'Supermarket',
  'Pharmacy',
  'Man Fashion',
  'Ladies Fashion',
  'Floral & Gift Shop',
  'Services',
  'Fashion Accessories',
  'Myanmar Traditional Fashion',
  'Speciality',
  'Electronics/HomeAppliances&MobilePhones',
  'Life Style & Hobbies',
  "Children's&Infants Fashion",
  'Play Ground',
  'Shoes & Bags',
  'Stationery & ToysPlay Ground',
  'Restaruants',
  'Bakery&Cafe/Beverage/IceCream&TakeAway',
  'Health & Beauty',
  'Edutainment & School',
];
